# Generated by Django 6.1.1 on 2026-09-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disagreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_ref', models.CharField(max_length=100)),
                ('reason', models.CharField(choices=[('missing_in_b', 'Missing in B'), ('orphan_b', 'Orphan B'), ('duplicate_b', 'Duplicate B'), ('value_mismatch', 'Value mismatch')], max_length=50)),
                ('system_a_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('system_b_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('location_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['record_ref', 'reason'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=100, unique=True)),
                ('org_id', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=100, unique=True)),
                ('location_id', models.CharField(blank=True, max_length=100)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('category_code', models.CharField(blank=True, max_length=100)),
                ('actor_id', models.CharField(blank=True, max_length=100)),
                ('base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('state', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SystemBRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=100, unique=True)),
                ('record_ref', models.CharField(blank=True, max_length=100)),
                ('normalized_record_ref', models.CharField(blank=True, max_length=100)),
                ('location_id', models.CharField(blank=True, max_length=100)),
                ('recorded_on', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('label', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
